- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/FrontPage.jsx
- frontend/src/components/Login.jsx
- frontend/src/components/Nav.jsx
- frontend/src/components/UserMenu.jsx
- frontend/src/index.css
- nginx/nginx.conf
- Redirect to front page on logout
- Remove border around banner on front page
- Add Nyrkiö css
- Improve note on user sign up
- Make sure nginx forwards unknown paths to SPA
- Add user menu in top navbar
> Various frontend changes

- frontend/src/components/Dashboard.jsx
> frontend/dashboard: Avoid blank page on missing commit message

- backend/api/api.py
- backend/tests/test_api.py
> backend/api: Fix HTTP DELETE

- frontend/src/App.jsx
- frontend/src/components/FrontPage.jsx
- frontend/src/components/Login.jsx
- frontend/src/components/Nav.jsx
- frontend/src/components/PricingPage.jsx
- frontend/src/components/SignUp.jsx
- frontend/src/index.css
First shot at a pricing page and dedicated sign up page.
> New pricing and sign up pages

- frontend/src/index.css
Also restore breadcrumbs and / as separator
> Modify hover colors

- frontend/src/components/PricingPage.jsx
- frontend/src/index.css
- frontend/vite.config.js
Blocker:Need to verify c7g produces stable results and we don't need dedicated instances.
> Dynamic pricing page

- frontend/src/docs/intro.md
(As opposed to author timestamp.)
> Doc: add the bash command to get the merge time of a commit.

- nginx/Dockerfile
- nginx/Dockerfile.dev
- nginx/static/robots.txt
- nginx/static/sitemap.xml
> nginx: Add robots.txt and sitemap.xml for crawlers

- backend/api/api.py
- backend/api/config.py
- backend/api/public.py
- backend/auth/auth.py
- backend/db/db.py
- backend/tests/test_api.py
- backend/tests/test_db.py
- frontend/src/App.jsx
- frontend/src/components/AdminDashboard.jsx
- frontend/src/components/Dashboard.jsx
- frontend/src/components/Nav.jsx
- frontend/src/components/PublicDashboard.jsx
- frontend/src/components/TestSettings.jsx
- frontend/src/index.css
- frontend/src/lib/utils.js
> Public test results

- frontend/src/components/Dashboard.jsx
- frontend/src/components/PricingPage.jsx
- frontend/src/index.css
PricingPage additions:
* Pay 12 month upfront
* Display text if engineering dept is unusually small
* Display text if company is 1000 employees or more
Note that last cómmit is unrelated, but was bothering me, so fixing it while here.
> Pricing rules

- frontend/src/components/Dashboard.jsx
This reverts commit c94223734e045aa1d58d57d89f9ea57d40ce2f46.
> Revert "Revert "Summarize Change Points: Improve CSS for small/mobile screens

- .gitignore
- frontend/package-lock.json
- frontend/package.json
- frontend/playwright.config.ts
- frontend/playwright.nyrkio.reporter.ts
- frontend/tests/logo.spec.ts
Adds 1 simple test: Check that the logo is on the front page
> Add Playwright for frontend testing + our very own Nyrkiö integration

- frontend/index.html
- frontend/src/index.css
Ironically it's a narrow font...
> new font for headings: Big Shoulders Text

- backend/api/api.py
- backend/api/background.py
- backend/api/changes.py
- backend/db/db.py
- backend/poetry.lock
- backend/pyproject.toml
- nginx/Dockerfile
- nginx/Dockerfile.dev
Work In Progress
Creating Pull Request for testing
> Background task to calculate cached change points

- backend/api/api.py
This reverts commit e311991e6c5b095c18da1aea4d700aea1bc3845c.
> Revert "backend/api: Disable precompute API"

- frontend/src/components/PricingPage.jsx
Note: This commit requires corresponding products to be setup on Stripe side:
simple_business_yearly
simple_business_monthly
simple_enterprise_yearly
simple_enterprise_monthly
> Simplify pricing

- frontend/src/components/LegendPage.jsx
- frontend/src/components/ProductPage.jsx
- frontend/src/components/SidePanel.jsx
- frontend/src/index.css
- Use the black and white nyyrikki image in background
- Use the colored nyyrikki only when visiting legend page
- Use the moss forest in the footer everywhere
- Use --nyrkio-dark-gray for boxes and frames around the UI
> Style changes

- frontend/src/App.jsx
- frontend/src/components/AdminDashboard.jsx
- frontend/src/components/ChangePointSummaryTable.jsx
- frontend/src/components/Dashboard.jsx
- frontend/src/components/DrawLineChart.jsx
- frontend/src/components/OrgDashboard.jsx
- frontend/src/components/TableOrResult.jsx
- frontend/src/index.css
- frontend/vite.config.js
If you append ?embed=yes to the URL, then headers, footers and menus will not be rendered, leaving you with just the main content, usually the graph, for that URL. This can be embedded into an iframe that is part of some internal or 3rd party dashboard.
> Support embedding graphs in iframe

- backend/api/changes.py
On a positive note, results were correct. But the incremental code would never use the cached results. It would fall back to a full recompute also when results had not changed.
> Fix: Incremental Hunter was not using cached change points

- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-staging.yml
- docker-compose.yml
- nginx/Dockerfile
- nginx/nginx.conf
Removes certbot from deployment chain
Seprate SSL cert for staging.nyrkio.com
> Use Namecheap SSL certs

- frontend/src/components/Dashboard.jsx
As mentioned in code comments, page structure is too complicated for React to follow. Yet one getElementsByClassName() is all you needed!
This is quite nice actually. Could do all of my React updates like this? Beats the obscure "I'll redraw the page lots of times for reasons you don't understand" :-D
> Populate summary div with tradition DOM methods

- frontend/src/components/DrawLineChart.jsx
In particular don't do both at the same time
> Chart: Change how to zoom and pan

- .github/workflows/deploy-prod-really.yml
- backend/notifiers/github.py
- frontend/src/components/Dashboard.jsx
Hard coded. Can be made configurable later.
> Limit points on a graph to 300.

- .github/workflows/deploy-prod-really.yml
> workflows: deploy-really: Remove dependency, it's a separate workflow now

- .github/workflows/deploy-prod-really.yml
> workflows: deploy-really: Put back the entire build part

- backend/api/public.py
- backend/api/pull_request.py
Notifications not possible/necessary
> public/pulls: Get changes for a public pull request

- backend/db/list_changes.py
> list_changes: regex needs the $ to not be open ended

- frontend/src/components/FrontPage.jsx
- frontend/src/index.css
> Just do the Youtube video with @media over several steps

- frontend/src/components/PullRequest.jsx
This reverts commit ebc91c0e6be08b1e194a699037d6844a3fab1869.
> Revert "fix: URI from where to fetch pulls"

- backend/github/marketplace.py
Otoh we need to keep the ordering, so can't use set() either.
Used list comprehension. David would be proud
> Can't use intersection() on list type

- backend/db/db.py
- backend/github/marketplace.py
TODO: Allow to set and manage a quota per month and day
> Get and verify Nyrkiö user and org that match the github counterparts

- backend/github/runner.py
> Needs str()
